### ISSUE TITLE
Mac M1 Docker error

### ISSUE THREAD

**Issue by renja-g** [fastapi/full-stack-fastapi-template#707] opened 2024-03-13 13:22 UTC
On my M1 I get the following error when trying to run `docker-compose.yml` via `docker compose up -d`:
```
 ! backend The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s
```

**Comment by dudil** [comment] 2024-03-13 17:09
Hi @renja-g, a quick fix would be to add the following line into the docker-compose.yml backend section:
``` yaml
...
...
build:
      context: ./backend
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    
    platform: linux/amd64 # Add this line for M1 Macs
...
...
```

@tiangolo , I will issue a PR for quickly fix that if you don't mind.

I'm not sure why the base image you are building from [tiangolo/uvicorn-gunicorn](https://hub.docker.com/r/tiangolo/uvicorn-gunicorn/tags) is marked as supporting only amd64,
The base image of that one is python:3.10 which also supports arm64.

**Comment by tiangolo** [comment] 2024-03-13 18:08
Thanks @dudil! :bow:  Thanks for the help and the fix!

@renja-g this was handled in https://github.com/tiangolo/full-stack-fastapi-template/pull/710 :nerd_face:

**Comment by dudil** [comment] 2024-03-13 19:39
@tiangolo - quick look for the root cause I found this is an issue with the GitHub action of [uvicorn-gunicorn-docker](https://github.com/tiangolo/uvicorn-gunicorn-docker).

There is an [open PR](https://github.com/tiangolo/uvicorn-gunicorn-docker/pull/93)  for fixing it but I'm not sure how much updated it is or still relevant.

However, seems like @tedvim who create the PR made a huge step forward and build a full registry of python stack images which are already multi-arch and updated https://github.com/multi-py
Switching the backend base image to be based on https://github.com/multi-py/python-gunicorn + fastapi, could push your amazing project forward and remove the need for you to maintain also the docker images.
I'll be more than happy to assist and make the fix if you think the same. 💐

**Comment by billzhong** [comment] 2024-04-09 22:04
Hi @dudil , seems like multi-arch support is added: https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker/pull/273 . So [your patch](https://github.com/tiangolo/full-stack-fastapi-template/pull/710) is not longer need. It would be nice to remove it to improve the performance at Apple Silicon.

**Comment by klipdassie** [comment] 2024-07-09 13:20
> Hi @dudil , seems like multi-arch support is added: [tiangolo/uvicorn-gunicorn-fastapi-docker#273](https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker/pull/273) . So [your patch](https://github.com/tiangolo/full-stack-fastapi-template/pull/710) is not longer need. It would be nice to remove it to improve the performance at Apple Silicon.

Thank you for pointing that out. I was using a non-Apple ARM system where the Docker Engine did not have the possibility to fallback to the AMD64 architecture, causing the image build to fail. After removing the patch, everything worked perfectly.

**Comment by dudil** [comment] 2024-07-09 13:50
Hi @klipdassie, thank you for that note 💐
As @billzhong had mentioned the base image now supports multi-arch so this patch is indeed no longer needed.
@tiangolo - I will remove it with a new PR so this issue could be resolved.

**Comment by tiangolo** [comment] 2024-09-20 15:05
It seems this is now handled, so I think we can close this issue now. :rocket: :cake:

**Closed by tiangolo** 2024-09-20 15:05 UTC
